fx_version 'cerulean'
game 'gta5'
lua54 'yes'

author 'gnsh'
description 'Universal City Infrastructure power grid, blackout, incident and repair framework'
version '0.38.0-rc.2'

-- All third-party resources are optional. Bridge adapters detect them at
-- runtime and switch to standalone/internal/memory fallbacks when absent.

ui_page 'web/index.html'

files {
    'web/index.html',
    'web/style.css',
    'web/app.js',
    'web/assets/gta-base-map.png',
    'web/assets/gta-native-districts.json',
}

shared_scripts {
    'config.lua',
    'shared/utilities.lua',
    'shared/constants.lua',
    'shared/types.lua',
    'shared/districts.lua',
    'shared/regions.lua',
    'shared/district_geometry.lua',
    'shared/grids.lua',
    'shared/feeders.lua',
    'shared/world_placement.lua',
    'shared/zone_resolver.lua',
    'profiles/sandy.lua',
    'profiles/ls_central.lua',
    'shared/visual_profile_resolver.lua',
    'bridge/core.lua',
    'bridge/framework/standalone.lua',
    'bridge/framework/qbcore.lua',
    'bridge/framework/qbox.lua',
    'bridge/framework/esx.lua',
    'shared/validators.lua',
}

client_scripts {
    'bridge/optional.lua',
    'bridge/target/menu_helper.lua',
    'bridge/target/standalone.lua',
    'bridge/target/none.lua',
    'bridge/target/qb_target.lua',
    'bridge/target/qtarget.lua',
    'bridge/target/ox_target.lua',
    'bridge/target/textui.lua',
    'bridge/ux/internal.lua',
    'bridge/notify/internal.lua',
    'bridge/notify/ox_lib.lua',
    'bridge/notify/framework.lua',
    'bridge/menu/internal.lua',
    'bridge/menu/ox_lib.lua',
    'bridge/menu/qb_menu.lua',
    'bridge/menu/menuv.lua',
    'bridge/progress/internal.lua',
    'bridge/progress/ox_lib.lua',
    'bridge/progress/progressbar.lua',
    'bridge/skillcheck/internal.lua',
    'bridge/skillcheck/ox_lib.lua',
    'bridge/skillcheck/qb_lock.lua',
    'bridge/nui.lua',
    'bridge/loader.lua',
    'client/state.lua',
    'client/metrics.lua',
    'client/zone_resolver.lua',
    'client/district_scanner.lua',
    'client/district_manager.lua',
    'client/visual/ownership.lua',
    'client/visual/native_blackout.lua',
    'client/visual/transition.lua',
    'client/visual/hybrid.lua',
    'client/visual/manager.lua',
    'client/sabotage.lua',
    'client/repair.lua',
    'client/debug.lua',
    'client/txadmin_auth.lua',
    'client/main.lua',
}

server_scripts {
    'server/logging.lua',
    'server/metrics.lua',
    'bridge/database/memory.lua',
    'bridge/database/oxmysql.lua',
    'bridge/inventory/none.lua',
    'bridge/inventory/ox_inventory.lua',
    'bridge/inventory/qb.lua',
    'bridge/inventory/qs.lua',
    'bridge/inventory/ps.lua',
    'bridge/inventory/framework.lua',
    'bridge/notify/internal.lua',
    'bridge/notify/ox_lib.lua',
    'bridge/notify/framework.lua',
    'bridge/nui.lua',
    'bridge/loader.lua',
    'server/persistence.lua',
    'server/security_manager.lua',
    'server/district_scan_export.lua',
    'server/zone_resolver.lua',
    'server/grid_manager.lua',
    'server/failure_manager.lua',
    'server/substation_manager.lua',
    'server/feeder_manager.lua',
    'server/transformer_manager.lua',
    'server/incident_impact.lua',
    'server/dispatch.lua',
    'server/incident_manager.lua',
    'server/interaction_manager.lua',
    'server/sabotage.lua',
    'server/repair_manager.lua',
    'server/power_calculator.lua',
    'server/api_helpers.lua',
    'server/replication.lua',
    'server/api.lua',
    'server/random_failure_manager.lua',
    'server/debug.lua',
    'server/admin_operations.lua',
    'server/main.lua',
}
